### ISSUE TITLE
dependency on cryptography pulls in rust on low-end systems

### ISSUE THREAD

**Issue by xloem** [mitya57/secretstorage#37]
In #6 the cryptographic backend was switched to "cryptography" .

It would be great if some other backend were available, as the cryptography package requires an install-time compile using rust on many systems, and secretstorage is a core package in the dependency tree of twine.

**Comment by mitya57** [comment]
Is [pycryptodome](https://pycryptodome.readthedocs.io/en/latest/) an option for you?

If yes, then I may consider switching from cryptography to it (which would mean reverting to the old code and updating the imports). When I moved to cryptography in 2016, it was not using Rust (it started using it 5 years later). And I don't remember the reasons why I did not use pycryptodome at that time — maybe because it was not packaged in my distro (Debian) at that point.

**Comment by xloem** [comment]
i ended up installing rust, but i was using pycryptodome up to that point :)

**Comment by mitya57** [comment]
Out of interest, what platform is that? Cryptography has pre-built binaries for the most popular platforms, and if it's not one of those, you will likely need to compile pycryptodome too. The only difference is language (C vs. rust).

Or maybe we can ask cryptography maintainers to provide binaries for your platform too?

**Comment by xloem** [comment]
I am not asking you to hop to and fix this, it is just a present issue.

I was running termux, an android posix-like environment. I also have some old x96s without network access.

Is rust normative to include with an operating system now? Linux distributions come with a c compiler; rust may have been added to this nowadays, I don't know.

**Comment by mitya57** [comment]
Sorry for the long delay.

Rust is not as normative as C, but Rust is considered to be more secure than C, so it's a better option for security-sensitive code (like cryptographic libraries).

As you managed to install Rust, and nobody else complained, I am going to close this issue.

By the way, I'm using Termux myself, but I did not need secretstorage there.
