### ISSUE TITLE
Collection.create_item() does not execute prompt

### ISSUE THREAD

**Issue by lovetox** [mitya57/secretstorage#39]
When executing create_item, and a prompt is returned, secretstorage does not check for it or execute it, which leads the following Item() return value to fail because the Item was not created.

**Comment by mitya57** [comment]
I have not seen this with gnome-keyring because this line always made sure that collection is unlocked:
https://github.com/mitya57/secretstorage/blob/338cbc77e167534b1d39d85eca031f4bf2b67e16/secretstorage/collection.py#L115

Looks like it's not the case with KeePassXC.

Can you please check if the linked commit (from `issue-39` branch) fixes the problem for you?

**Comment by lovetox** [comment]
Thanks i will test this later

**Comment by lovetox** [comment]
Hi, tested and works for me.

**Comment by mitya57** [comment]
Ok, pushed to master. Do you want a new release?

**Comment by lovetox** [comment]
It would be great if there would be a release sometime before or at the same time as python-keyring, seeing that the KeepassXC support landed there now.

Thanks

**Comment by mitya57** [comment]
New version 3.3.3 is released now.
